2020-01-05 15:14:46,178 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-05 15:14:51,250 [INFO ]  Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
2020-01-05 15:14:57,880 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/favicon.ico'
Traceback (most recent call last):
  File "/home/hungdv/anaconda3/envs/venv/lib/python3.6/site-packages/sanic/app.py", line 918, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/hungdv/anaconda3/envs/venv/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/hungdv/anaconda3/envs/venv/lib/python3.6/site-packages/sanic/router.py", line 470, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found